New rule: Adds `private` modifier to @State vars
nicklockwood/SwiftFormat pull request #1852
Opened 2024-09-09 18:30 UTC by davepaul0

Hi! I'm proposing this new rule, per Apple's recommendation that `@State` variables remain private to their view.
If desired, we could also expand this rule to cover other SwiftUI property wrappers that should be private, like `@Environment` and `@StateObject`

Feel free to close if you feel that this is too domain specific or too lint-y.

2024-09-11 06:57 UTC, nicklockwood requested changes
Thanks! just a couple of comments on the implementation

2024-09-11 06:57 UTC, nicklockwood commented on Sources/Tokenizer.swift
> +        guard case let .keyword(keyword) = self else {
I suspect this approach doesn't work for cases like "package" because these are contextual keywords (keywords that were added to the language later and so are allowed to be used as identifiers) and so are parsed as identifiers rather than keywords.

In any case, it's probably better to use the existing modifiers parsing mechanisms in ParsingHelpers, which correctly handle things like `private(set)` and property wrappers with arguments, etc.

2024-09-11 06:57 UTC, nicklockwood commented on Tests/RulesTests+SwiftUI.swift
> +    }
These are good, but you should also add tests for cases like `public private(set)` and `package`

2024-09-11 21:25 UTC, davepaul0 commented on Sources/Tokenizer.swift
> +        guard case let .keyword(keyword) = self else {
oops! I completely missed the existing helpers. I'll revert this.

2024-09-13 18:29 UTC, davepaul0 reviewed
@nicklockwood should be good to go, thanks!
* expanded the rule to include `@StateObject` as well
* used existing ACL modifier helpers and added test cases
* some naming cleanup

2024-09-14 09:48 UTC, merged