[Feature] Add support for JSON output
nicklockwood/SwiftFormat pull request #900
Opened 2021-04-09 19:21 UTC by danyf90

Fix for https://github.com/nicklockwood/SwiftFormat/issues/890

The JSON format is inspired by the format of SwiftLint JSON reporter

2021-04-09 22:32 UTC, nicklockwood commented
Looks good. I think I'd prefer to follow SwiftLint's pattern of `--reporter json` for the CLI argument though, as it will make it easier to add additional formats in future.

2021-04-11 13:32 UTC, danyf90 commented
Thanks for the review @nicklockwood , can you have a look now? 🙌

2021-04-11 22:13 UTC, nicklockwood requested changes

2021-04-11 22:13 UTC, nicklockwood commented on Sources/CommandLine.swift
> +    --reporter-output  Reporter output file (defaults to `output.<reporter>`)
The `--reporter-output` parameter seems redundant - we can just re-use the existing `--output` parameter.

Also, the output shouldn't default to a hard-coded filename if no output file is specified, it should just write the json to stdout.

2021-04-11 22:13 UTC, nicklockwood commented on Sources/CommandLine.swift
> +            let outputFile = args["reporter-output"] ?? "output.\(reporter)"
Instead of inferring output file from reporter, we could infer the reporter from the output file, so if the user specifies an output file with a json extension it could preselect json as the exporter type.

2021-04-11 22:13 UTC, nicklockwood commented on Sources/JSONReporter.swift
> +    try container.encode(self.filePath ?? "", forKey: .file)
Does it make sense to write a blank string if the filePath is nil rather than just omitting the key?

2021-04-11 22:13 UTC, nicklockwood commented on Sources/JSONReporter.swift
> +    case rule_id
I'd prefer to us camelCase here, in accordance with Swift naming conventions:

```swift
case ruleID = "rule_id"
```

2021-04-12 18:51 UTC, danyf90 commented on Sources/CommandLine.swift
> +    --reporter-output  Reporter output file (defaults to `output.<reporter>`)
Isn't `--output` the output of the formatted file? reusing it here would be a bit confusing 🤔 
```
    --output           Output path for formatted file(s) (defaults to input path)
```

What about having just a `--report` parameter, and determine the type from the provided file extension?

2021-04-12 18:54 UTC, danyf90 commented on Sources/CommandLine.swift
> +            let outputFile = args["reporter-output"] ?? "output.\(reporter)"
✅

2021-04-12 18:55 UTC, danyf90 commented on Sources/CommandLine.swift
> +    --reporter-output  Reporter output file (defaults to `output.<reporter>`)
Replaced `reporter` and `reporter-output` with single `report` parameter (from which also the type can be inferred in the future.
Please let me know whether it is fine 🙌

2021-04-12 20:33 UTC, nicklockwood commented on Sources/CommandLine.swift
> +    --reporter-output  Reporter output file (defaults to `output.<reporter>`)
The problem with that is that if you don't specify an --output file then there's no way for it to infer what format should be sent to stdout.

2021-04-13 06:23 UTC, danyf90 commented on Sources/CommandLine.swift
> +    --reporter-output  Reporter output file (defaults to `output.<reporter>`)
The `--report` parameters tales in input the report file, not the type, so you can use it as:
```
swiftformat <whatever option> --report report.json
```

So when printing the json report the rest of the output and the parameters are not affected.

What do you think?

2021-04-13 06:24 UTC, danyf90 commented on Sources/JSONReporter.swift
> +    case rule_id
✅

2021-04-13 06:24 UTC, danyf90 commented on Sources/JSONReporter.swift
> +    try container.encode(self.filePath ?? "", forKey: .file)
✅

2021-04-15 07:16 UTC, danyf90 commented on Sources/CommandLine.swift
> +    --reporter-output  Reporter output file (defaults to `output.<reporter>`)
@nicklockwood did you had time to have a look at this?
Not urgent at all, just wanted to be sure you didn't miss my message 🙌

2021-04-15 10:47 UTC, nicklockwood commented on Sources/CommandLine.swift
> +    --reporter-output  Reporter output file (defaults to `output.<reporter>`)
Hmm, I was under the impression that reporting was only applicable when running in --lint mode, in which case --output is unused, so having --report take a separate path seemed redundant. But I now realize that you're intending for report to work even when formatting? In which case I agree a separate --report path makes sense.

2021-04-15 15:45 UTC, danyf90 commented on Sources/CommandLine.swift
> +    --reporter-output  Reporter output file (defaults to `output.<reporter>`)
For my use case I would use it only for linting, but I think having a separate parameter may be more generic and cover more use cases 🙌

2021-04-16 21:27 UTC, merged